version: 0.0.0.{build}

# Build worker image (VM template)
image: Visual Studio 2017
  
# tasks
before_build:
- cmd: .paket\paket.exe restore

build_script:
- cmd: >-
    ./build.bat all

test: off

artifacts:
- path: build
  name: statsbot
